name: Export OpenZFS docs for NotebookLM
on:
  workflow_dispatch: {}   # run it manually

jobs:
  build-text:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.x' }
      - name: Install Sphinx & doc deps
        run: |
          python -m pip install -U pip
          python -m pip install -r docs/requirements.txt
      - name: Build Sphinx text & split into NotebookLM chunks
        working-directory: docs
        run: |
          make text
          python - <<'PY'
          import glob, pathlib
          files = sorted(glob.glob('_build/text/*.txt'))
          text = '\n\n'.join(open(f, encoding='utf-8', errors='ignore').read() for f in files)
          words = text.split()
          CHUNK = 400_000  # keep well under NotebookLM's 500k/source cap
          out = pathlib.Path('_build/notebooklm'); out.mkdir(parents=True, exist_ok=True)
          for i in range(0, len(words), CHUNK):
              (out / f'openzfs-docs-{i//CHUNK+1:02}.txt').write_text(' '.join(words[i:i+CHUNK]), encoding='utf-8')
          PY
      - name: Upload TXT artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openzfs-notebooklm-txt
          path: docs/_build/notebooklm/*.txt
